name: Post-merge Build, Test and Report

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  push:
    branches:
      - main

  workflow_dispatch:

env: # Only adding the variables in that are required for
  IPV_STUB_URL: ${{ secrets.IPV_STUB_URL }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    continue-on-error: true


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Build Test CIC Front Image
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SH_BAV_ACCESS_TOKEN }} # if needed

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test:browser:ci # will run `yarn test:browser:ci` command

      - name: Generate HTML Report
        if: failure()
        run: yarn test:browser:report
      - uses: actions/upload-artifact@v3
        with:
          name: bav-cri-test-report
          path: test/reports/bav-reports
