name: Post merge checks

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IPV_STUB_URL: ${{ secrets.IPV_STUB_URL }}
  API_BASE_URL: ${{ secrets.API_BASE_URL }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    continue-on-error: true

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Checks if committing secrets to repo
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: "detect-secrets --all-files"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Run test and write coverage
        run: npm run test

      - name: "Run SonarCloud Scan"
        if: success() && github.actor != 'dependabot[bot]'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies (npm)
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SH_BAV_ACCESS_TOKEN }}

      - name: Build production bundle
        run: npm run build

      - name: Test the app
        id: bavBrowserTests
        run: npm run test:browser:ci

      - name: Generate HTML Report
        if: always() && steps.bavBrowserTests.outcome == 'failure'
        run: npm run test:browser:report

      - uses: actions/upload-artifact@v4
        if: always() && steps.bavBrowserTests.outcome == 'failure'
        with:
          name: bav-cri-test-report
          path: test/reports/bav-reports
