name: Post merge checks

on:
  workflow_dispatch:
  push:
    branches:
      - main

env: # Only adding the variables in that are required for
  IPV_STUB_URL: ${{ secrets.IPV_STUB_URL }}
  API_BASE_URL: ${{ secrets.API_BASE_URL }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    continue-on-error: true


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Build Test CIC Front Image
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SH_BAV_ACCESS_TOKEN }} # if needed

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

      - name: Test the app
        id: bavBrowserTests
        uses: borales/actions-yarn@v4
        with:
          cmd: test:browser:ci # will run `yarn test:browser:ci` command

      - name: Generate HTML Report
        if: always() && steps.bavBrowserTests.outcome == 'failure'
        run: yarn test:browser:report
      - uses: actions/upload-artifact@v3
        if: always() && steps.bavBrowserTests.outcome == 'failure'
        with:
          name: bav-cri-test-report
          path: test/reports/bav-reports
