name: pre-commit

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Install Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.x'

    - name: Checks for secrets
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: "detect-secrets --all-files"

    - name: Cache dependencies
      uses: actions/cache@v4.0.0