name: pre-commit

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache build
      if: ${{ always() }}
      id: cache-commom-lambda-build
      uses: actions/cache/save@v4
      with:
        path: |
          out/
        key: "${{ github.sha }}"

    - name: Checks for secrets
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: "detect-secrets --all-files"

    - name: Cache restore
      uses: actions/cache/restore@v4
      with:
        path: |
          out/
        key: "${{ github.sha }}"